### ISSUE TITLE
About positional embedding

### ISSUE THREAD

**Issue by makabaka987** [daiquocnguyen/R-MeN#1]
Thank you for your code. It is very helpful to me, but I have some questions. What is positional embedding ? How do you initialize it ?

**Comment by daiquocnguyen** [comment]
Hi,

I want to make use of _the order of "head, relation and tail"_ within each triple. Thus, I add to each position a positional embedding to induce the order.

Three positional embeddings are model parameters, which is initialized using the Glorot initialization (i.e., "tf xavier_initializer" in the second-last line in "model...py").
