### ISSUE TITLE
About decoder

### ISSUE THREAD

**Issue by makabaka987** [daiquocnguyen/R-MeN#2]
I would like to ask about how the decoder is implemented, is there any detailed code? Thank you !

**Comment by daiquocnguyen** [comment]
You can see the detailed code of the decoder at Line 50 in https://github.com/daiquocnguyen/R-MeN/blob/master/RMeN_tf/model_R_MeN_TripleCls_CNN.py

or Line 83 in https://github.com/daiquocnguyen/R-MeN/blob/master/RMeN_pytorch/RMeN.py
