### ISSUE TITLE
What are "relation2vec50.init" and "entity2vec50.init"?

### ISSUE THREAD

**Issue by Ironeie** [daiquocnguyen/R-MeN#3]
These 2 files are not in the original WN11 and FB13 dataset, can you tell us what they are and how did you get them? Thx

**Comment by daiquocnguyen** [comment]
For WN11, we initialize entity and relation embeddings in our R-MeN by averaging word vectors in the relations and entities, in which these word vectors are taken from the Glove 50-dimensional pre-trained embeddings.
For FB13, we use entity and relation embeddings produced by TransE to initialize entity and relation embeddings in our R-MeN. You can see the details in Section 3.2.1 in our paper.
